// <auto-generated />
namespace InterviewQ.Resources.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class TestAndTestQU : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TestAndTestQU));
        
        string IMigrationMetadata.Id
        {
            get { return "201409071322243_TestAndTestQU"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
